services:
  postgres:
    image: postgres:16-alpine
    container_name: votacao-postgres
    environment:
      POSTGRES_DB: votacao
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - votacao-postgres-data:/var/lib/postgresql/data
      - ./scripts/database/01-create-schema.sql:/docker-entrypoint-initdb.d/01-create-schema.sql:ro

  kafka:
    image: apache/kafka:3.7.2
    container_name: votacao-kafka
    profiles:
      - kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "19092:19092"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: votacao-kafka-ui
    profiles:
      - kafka
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: votacao-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: "true"
    ports:
      - "8084:8080"

volumes:
  votacao-postgres-data:
